name: Code Formatter

on:
  push:

jobs:
  PEP8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: |
          python -m pip install --upgrade pip
          pip install autoflake isort black

      - run: autoflake --in-place --recursive --remove-all-unused-imports --ignore-init-module-imports .

      - run: isort .

      - run: black .
